[application]
asset_dir = "assets"

[web.app]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
