[application]

[web.app]

# HTML title tag content
title = "Tim Forrer"

# include `assets` in web platform
[web.resource]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
