spin_manifest_version = 2

[application]
name = "website"
version = "0.1.0"
authors = ["Tim Forrer <timforrer16@gmail.com>"]
description = "Personal portfolio website"

[[trigger.http]]
route = "/..."
component = "website"

[component.website]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [ { source = "./target/dx/website/release/web/public", destination = "/" } ]
[component.website.build]
command = """
npx @tailwindcss/cli -i ./tailwind.css -o ./assets/tailwind.css \
&& dx bundle --platform web
"""
watch = ["src/**/*.rs", "Cargo.toml", "./tailwind.css"]
[component.website.environment]
FALLBACK_PATH = "index.html"
